### ISSUE TITLE
question about the code

### ISSUE THREAD

**Issue by changapple** [stone96123/DPM#1]
Dear fellow,

I am a student reproducing the code of DPM, I meet a code error in metrics.py.  I don't know why this function could not find the tensor, is there anything that I missed to download or something?

<img width="1115" alt="question" src="https://user-images.githubusercontent.com/77925522/195394060-8b721bda-cf5f-4309-ac91-af63a6c98c0c.png">

**Comment by stone96123** [comment]
It seems that the feature hasn't been updated in this function. In this code version, this processing will be automatic in the processor.py. I don't know if you have revised the part since it does not occur in the released version.

**Comment by changapple** [comment]
However, in the processor.py, the val_dataloader is empty, the length is 0, I don't know why.

**Comment by stone96123** [comment]
Have you already prepared the dataset and imported the validation dataset? Under the right setting the table will like:
![image](https://user-images.githubusercontent.com/33454627/196084724-508ef984-4c9f-4394-ae59-6cd812599b2a.png)
if not, the query and gallery will go to 0.

**Comment by changapple** [comment]
Yes, I find out that the table goes to 0, however, I also find out the link you provide for the Occ_ReID is the one of Occ_Duke? The baidu disk link gives the Occ_ReID but the name of the folder does not match the code. This confuse me a lot. 
Besides, may I add your wechat so that I could ask more precise questions, I think this comment box is not very convenient.

**Comment by changapple** [comment]
为了表达清楚我还是用中文写一遍吧，我发现readme里面给的Occ_ReID 的google drive的链接是Occ_Duke的，而百度网盘的链接给的是Occ_ReID的。我用Occ_ReID这个数据集试验了一下发现会有文件夹找不到，所以我交换了两个数据集的名字发现不会在寻找数据文件夹名字那里报错了。但是数据仍然读取不了，我不明白这是为什么。还有就是能不能加个微信，我就是想方便问问题，除了询问DPM的问题我不会打扰到您的。

**Comment by stone96123** [comment]
因为我用的是market的dataloader改的，因此，你需要按照market的命名规则去改一下occluded-ReID的数据中样本的命名。另外我的微信是13260512596

**Comment by changapple** [comment]
我是apple，我加你啦！我还是不太明白怎么去更改样本的命名唉，看到的话通过一下呗
