### ISSUE TITLE
Could You provide the performance results under the setting: STRIDE_SIZE: [16, 16]

### ISSUE THREAD

**Issue by WangTaoAs** [stone96123/DPM#2]
Dear Author:
  I found that the ViT is under the sliding window setting in dmp.yml (STRIDE_SIZE: [11, 11]), and a smaller STRIDE could provide a 
  higher performance.
  So Could provide the performance under the STRIDE_SIZE: [16, 16] to further explain the effectiveness in this case

  Thank You very much~

**Comment by stone96123** [comment]
Thanks for your suggestion, as we claim in this paper, we just follow the stride setting of TranReID. Therefore, we have not evaluated under the stride of [16,16]. If you are interested in the results, you can change the stride setting in configs/OCC_Duke/dpm.py and run this code by yourself.
