### ISSUE TITLE
使用Occluded-REID的预训练模型进行测试达不到论文中的效果

### ISSUE THREAD

**Issue by changshuowang** [stone96123/DPM#3]
作者您好：
        感谢您做出如此优秀的工作👍但是我在使用您的预训练模型的时候，发现occ_duke的预训练模型能够达到论文的结果，但是Occluded-REID的预训练模型达不到。
下图所示是我用该项目的Occluded-REID的预训练模型测试的结果，离论文中的R-1：85.5 和mAP：79.7还有一定的差距。所以我在想是作者放错了预训练模型，还是我数据读取的时候出现了错误，因为我看到你在其他问题中说你处理了数据集的名称，我也处理了，可否截图让我看看您处理后的数据名称是什么格式的，并且您的Occluded-REID的dalaloder的pid和camid是怎么获得的？
![image](https://user-images.githubusercontent.com/49676110/201492203-930a9b0b-9f5c-4afe-93a7-77aace7d19ae.png)
期待您的回复。

**Comment by stone96123** [comment]
这个可能跟命名规则有关，为了方便，我在main路径下上传了Rename.py文件。该文件需要手动放到Occluded-REID文件夹下运行一次，即可获得重新命名后的数据集，然后就用新数据集测试即可

**Comment by changshuowang** [comment]
> 
感谢作者，使用了您的命名规则后，准确率达到了您公布的结果。十分感谢你的帮助。
