### ISSUE TITLE
About Occluded-Duke and DukeMTMC

### ISSUE THREAD

**Issue by changshuowang** [stone96123/DPM#4]
作者您好，我看到datasets文件夹里的dukemtmcreid.py和occ_duke.py相同，都是从self.dataset_url = 'http://vision.cs.duke.edu/DukeMTMC/data/misc/DukeMTMC-reID.zip'这个链接里下载的数据集，所以我不太了解 Occluded-Duke为什么跟 DukeMTMC数据集相同，然而DPM的结果却不同？或者是我哪里漏掉了细节吗？

**Comment by stone96123** [comment]
这两个并不是完全一样的数据集，但是occluded-duke来自于DukeMTMC数据集，因此使用了同样的url。

**Comment by changshuowang** [comment]
> 这两个并不是完全一样的数据集，但是occluded-duke来自于DukeMTMC数据集，因此使用了同样的url。

感谢这么快回复，我明白了，那我去CSDN或者百度一下下载一个occluded-duke数据集
