### ISSUE TITLE
作者您好，我通过复现您的代码，occluded-reid直接下载您提供的模型进行测试，性能为map：76.6、rank1:82.7，和论文中提到的出入有点大。我觉得应该是我个人复现的实验和您的方法有些偏差，能否提供下您在occluded-reid上的实验代码，我好再您的工作上继续做下去，非常感谢，邮箱：1392585506@qq.com

### ISSUE THREAD

**Issue by LGR927** [stone96123/DPM#5]

**Comment by stone96123** [comment]
非常感谢对于我们工作的关注，这个地方代码是完全一样的，我们有在论文中讲到如果要训练occluded-reid需要将datasets/make_dataloader.py中的T.ColorJitter打开，然后将loss/make_loss.py中orthonomal_loss权重设置为0.01，就能够实现相应的结果，我们也有提供测试模型可供直接下载

**Comment by LGR927** [comment]
非常感谢您的回复，我已经基本复现出论文中的效果，还有一个小疑问，就是occluded_reid中没有关于相机参数cmid的信息，我是取query的cmid=0，gallery的cmid=2时可以达到和论文接近的效果，请问下您在实验中也是类似这样处理cmid的标签信息吗？还是说有别的方法

**Comment by stone96123** [comment]
你可以参考issue#3，main路径下有一个Rename.py文件，是我在训练时处理occluded-reid数据集的方式。该文件需要手动放到Occluded-REID文件夹下运行一次，即可获得重新命名后的数据集，然后就用命名好的新数据集测试即可。

**Comment by LGR927** [comment]
明白啦，再次感谢您的解答！
